version: '3'
services:
 #   db:
 #     build: Dockerfiles/postgis/
 #     volumes:
 #       - ./pg:/var/lib/postgresql
 #     # WARNING: THIS IS UNSAFE USE ONLY FOR DEV
 #     ports:
 #       - "0.0.0.0:5432:5432"
 #     environment:
 #       - POSTGRES_USER=docker
 #       - POSTGRES_PASSWORD=docker
 #     #restart: on-failure:5
    django:
      build: .
      volumes:
        - '.:/usr/src/app'
        - static-volume:/usr/src/app/static_root
      command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
      ports:
        - "8000:8000"
      environment:
        - DEBUG=True
        - URBANMAP_DATABASE_NAME=urban_locality_cadastre
        - URBANMAP_DATABASE_USER=docker
        - URBANMAP_DATABASE_PASSWORD=docker
        - URBANMAP_DATABASE_HOST=host.docker.internal
        - URBANMAP_DATABASE_PORT=5432
    nginx:
      image: nginx:latest
      ports:         
        - 80:80
      depends_on:
        - django
      volumes:         
        - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
        - static-volume:/usr/src/app/static_root

volumes:
     static-volume: 
